server:
  port: 8081

logging:
  file:
    path: ./logs  # 可设置为绝对路径
  level:
    root: INFO
    com.felixcjy: DEBUG
    org.springframework: DEBUG
    org.springframework.web: DEBUG
    org.springframework.transaction.interceptor: DEBUG
    org.springframework.jdbc.datasource.DataSourceTransactionManager: DEBUG