server:
  port: 8080

logging:
  level:
    root: INFO
    com.felixcjy: DEBUG
    org.springframework: WARN
    org.springframework.web: DEBUG

# 数据源配置
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.228.132:3306/super_clay?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: Fxsd1100
    druid:
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
      # 初始连接数
      initialSize: 5
      # 最小连接池数量
      minIdle: 10
      # 最大连接池数量
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置连接超时时间
      connectTimeout: 30000
      # 配置网络超时时间
      socketTimeout: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      # 配置一个连接在池中最大生存的时间，单位是毫秒
      maxEvictableIdleTimeMillis: 900000
      # 配置检测连接是否有效
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      webStatFilter:
        enabled: true
      statViewServlet:
        enabled: true
        # 设置白名单，不填则允许所有访问
        allow:
        url-pattern: /druid/*
        # 控制台管理用户名和密码
        login-username: felix
        login-password: Fxsd1100
      filter:
        stat:
          enabled: true
          # 慢SQL记录
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: true
        wall:
          config:
            multi-statement-allow: true
  redis:
    host: 192.168.228.132
    port: 6379
    password: Fxsd1100
    database: 0
    lettuce:
      pool:
        max-active: 8 # 最大活跃连接数
        max-idle: 8 # 最大空闲连接数
        min-idle: 0 # 最小空闲连接数

# 启用/禁用 Arthas
arthas:
  enabled: true
  # 设置 Arthas Agent 的通信端口
  telnet-port: 3658
  http-port: 8563

# Swagger 页面路径
springdoc:
  api-docs:
    path: /v3/api-docs # 修改 API 文档路径（默认 /v3/api-docs）
  swagger-ui:
    path: /swagger-ui.html # 修改 Swagger UI 路径

mybatis-plus:
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  typeAliasesPackage: org.felixcjy.**.domain.entity
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl